.TH "Hotel.ListaPokoi" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.ListaPokoi \- Klasa ListaPokoi zawiera informacje na temat zagreogwanej ilości pokoi i pozwala dokonywać operacji na tychże\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListaPokoi\fP (List< \fBPokoj\fP > lista)"
.br
.ti -1c
.RI "\fBPokoj\fP \fBWybierzPokoj\fP (string idpokoju)"
.br
.RI "Metoda ma na celu wybór pokoju o podanym ID\&. "
.ti -1c
.RI "\fBPokoj\fP? \fBWybierzPokojAutomatycznie\fP (int rozmiar, DateTime poczatek, DateTime koniec)"
.br
.RI "Metoda ma na celu wybranie pokoju w sposób automatyczny (jeśli jest to możliwe)\&. Przyjmuje informacje o: "
.ti -1c
.RI "void \fBZapisXml\fP (string nazwaPliku)"
.br
.RI "Metoda ma na celu dokonanie zapisu informacji zawartych w instancji klasy ListaPokoi do pliku XML\&.\&.\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Metoda ma na celu zwrócenie informacji na temat pokoi znajdujących się w liście\&. "
.ti -1c
.RI "\fBPokoj\fP \fBZnajdzWolnyPokoj\fP (int liczbaOsob)"
.br
.RI "Metoda ma na celu znalezienie wolengo pokoju o podanej ilości osób\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< \fBPokoj\fP > \fBFiltrujPokojePoGosciach\fP (\fBGosc\fP gosc, \fBRejestrGosci\fP rejestr)"
.br
.RI "Metoda ma za zadanie znaleźć pokoje w podanym rejestrze, w których bytował, bytuje lub bytował będzie podany gość\&. "
.ti -1c
.RI "static List< \fBPokoj\fP > \fBFiltrujPokojePoDacie\fP (DateTime data, \fBRejestrGosci\fP rejestr)"
.br
.RI "Metoda ma na celu znalezienie pokoi w podanym rejestrze, które są okupowane w podanym czasie (pojedyncza data)\&. "
.ti -1c
.RI "static List< \fBPokoj\fP > \fBPokojeZajeteWPodanymCzasie\fP (DateTime poczatek, DateTime koniec, \fBRejestrGosci\fP rejestr)"
.br
.RI "Metoda ma na celu znalezienie pokoi w podanym rejestrze, które w podanym zakresie czasu są okupowane\&. "
.ti -1c
.RI "static ? \fBListaPokoi\fP \fBOdczytXml\fP (string nazwaPliku)"
.br
.RI "Metoda ma na celu odczyt informacji zapisanych jako lista pokoi z pliku XML\&.\&.\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBPokoj\fP > \fBpokoje\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Klasa ListaPokoi zawiera informacje na temat zagreogwanej ilości pokoi i pozwala dokonywać operacji na tychże\&. 
.SH "Member Function Documentation"
.PP 
.SS "static List< \fBPokoj\fP > Hotel\&.ListaPokoi\&.FiltrujPokojePoDacie (DateTime data, \fBRejestrGosci\fP rejestr)\fC [inline]\fP, \fC [static]\fP"

.PP
Metoda ma na celu znalezienie pokoi w podanym rejestrze, które są okupowane w podanym czasie (pojedyncza data)\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data\&. 
.br
\fIrejestr\fP Rejestr\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Lista pokoi\&. 
.RE
.PP

.SS "static List< \fBPokoj\fP > Hotel\&.ListaPokoi\&.FiltrujPokojePoGosciach (\fBGosc\fP gosc, \fBRejestrGosci\fP rejestr)\fC [inline]\fP, \fC [static]\fP"

.PP
Metoda ma za zadanie znaleźć pokoje w podanym rejestrze, w których bytował, bytuje lub bytował będzie podany gość\&. 
.PP
\fBParameters\fP
.RS 4
\fIgosc\fP Gość\&. 
.br
\fIrejestr\fP Rejstr gości\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Lista pokoi\&. 
.RE
.PP

.SS "static ? \fBListaPokoi\fP Hotel\&.ListaPokoi\&.OdczytXml (string nazwaPliku)\fC [inline]\fP, \fC [static]\fP"

.PP
Metoda ma na celu odczyt informacji zapisanych jako lista pokoi z pliku XML\&.\&.\&. 
.PP
\fBParameters\fP
.RS 4
\fInazwaPliku\fP \&.\&.\&. o podanej nazwie\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Lista pokoi\&. 
.RE
.PP

.SS "static List< \fBPokoj\fP > Hotel\&.ListaPokoi\&.PokojeZajeteWPodanymCzasie (DateTime poczatek, DateTime koniec, \fBRejestrGosci\fP rejestr)\fC [inline]\fP, \fC [static]\fP"

.PP
Metoda ma na celu znalezienie pokoi w podanym rejestrze, które w podanym zakresie czasu są okupowane\&. 
.PP
\fBParameters\fP
.RS 4
\fIpoczatek\fP Początkowa data\&. 
.br
\fIkoniec\fP Data końcowa\&. 
.br
\fIrejestr\fP Rejestr\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Lista pokoi\&. 
.RE
.PP

.SS "override string Hotel\&.ListaPokoi\&.ToString ()\fC [inline]\fP"

.PP
Metoda ma na celu zwrócenie informacji na temat pokoi znajdujących się w liście\&. 
.PP
\fBReturns\fP
.RS 4
Tekst\&. 
.RE
.PP

.SS "\fBPokoj\fP Hotel\&.ListaPokoi\&.WybierzPokoj (string idpokoju)\fC [inline]\fP"

.PP
Metoda ma na celu wybór pokoju o podanym ID\&. 
.PP
\fBParameters\fP
.RS 4
\fIidpokoju\fP ID pokoju\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pokój\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBrakPokojuException\fP 
.RE
.PP

.SS "\fBPokoj\fP? Hotel\&.ListaPokoi\&.WybierzPokojAutomatycznie (int rozmiar, DateTime poczatek, DateTime koniec)\fC [inline]\fP"

.PP
Metoda ma na celu wybranie pokoju w sposób automatyczny (jeśli jest to możliwe)\&. Przyjmuje informacje o: 
.PP
\fBParameters\fP
.RS 4
\fIrozmiar\fP - liczbie gości, 
.br
\fIpoczatek\fP - początku trwanie planowanego pobytu, 
.br
\fIkoniec\fP - końcu planowanego pobytu\&.
.RE
.PP
\fBReturns\fP
.RS 4
Pokój, który spełnia podane warunki, jeśli ten istnieje\&. 
.RE
.PP

.SS "void Hotel\&.ListaPokoi\&.ZapisXml (string nazwaPliku)\fC [inline]\fP"

.PP
Metoda ma na celu dokonanie zapisu informacji zawartych w instancji klasy ListaPokoi do pliku XML\&.\&.\&. 
.PP
\fBParameters\fP
.RS 4
\fInazwaPliku\fP \&.\&.\&. o podanej nazwie\&. 
.RE
.PP

.SS "\fBPokoj\fP Hotel\&.ListaPokoi\&.ZnajdzWolnyPokoj (int liczbaOsob)\fC [inline]\fP"

.PP
Metoda ma na celu znalezienie wolengo pokoju o podanej ilości osób\&. 
.PP
\fBParameters\fP
.RS 4
\fIliczbaOsob\fP ilość osób\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pokój\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBrakPokojuException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
