.TH "Hotel.ZlyPeselException" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.ZlyPeselException \- Wyjątek wywoływany jest w sytuacji, kiedy podano nieprawidłowy pesel\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Wyjątek wywoływany jest w sytuacji, kiedy podano nieprawidłowy pesel\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
