.TH "Hotel.DodajGoscia" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.DodajGoscia \- Logika interakcji dla klasy DodajGoscia\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDodajGoscia\fP (\fBRejestrGosci\fP rejestr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logika interakcji dla klasy DodajGoscia\&.xaml\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
