.TH "Hotel.ListaPobytow" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.ListaPobytow \- Logika interakcji dla klasy ListaPobytow\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SH "Detailed Description"
.PP 
Logika interakcji dla klasy ListaPobytow\&.xaml\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
