.TH "Hotel" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdres\fP"
.br
.RI "Klasa Adres ma za zadanie przechowanie informacji na temat adresu osób\&. "
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml\&. "
.ti -1c
.RI "class \fBBrakPokojuException\fP"
.br
.RI "Wyjątek jest wywoływany w sytuacji, kiedy pokój, do którego pragniemy się odwołać nie istnieje\&. "
.ti -1c
.RI "class \fBDodajGoscia\fP"
.br
.RI "Logika interakcji dla klasy DodajGoscia\&.xaml\&. "
.ti -1c
.RI "class \fBDodajRezerwacje\fP"
.br
.RI "Logika interakcji dla klasy DodajRezerwacje\&.xaml\&. "
.ti -1c
.RI "class \fBGosc\fP"
.br
.RI "Klasa gość ma za zadanie przechowywanie informacji na temat gościa oraz zezwolić m\&. in\&. na wybór warunków rezerwacji\&. "
.ti -1c
.RI "class \fBKadra\fP"
.br
.RI "Klasa kadra przechowuje informacje na temat kadry pracowników\&. Pozwala na zapis i odczyt listy, poszerzenie jej o nowych pracowników i znajdywanie tych, którzy spełniają zadane warunki\&. "
.ti -1c
.RI "class \fBListaPobytow\fP"
.br
.RI "Logika interakcji dla klasy ListaPobytow\&.xaml\&. "
.ti -1c
.RI "class \fBListaPokoi\fP"
.br
.RI "Klasa ListaPokoi zawiera informacje na temat zagreogwanej ilości pokoi i pozwala dokonywać operacji na tychże\&. "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml\&. "
.ti -1c
.RI "class \fBNieprawidlowyNumerException\fP"
.br
.RI "Wyjątek wywoływany jest w sytuacji kiedy podano nieprawidłowy numer (lokalu lub domu) "
.ti -1c
.RI "class \fBOsoba\fP"
.br
.RI "Osoba reprezentuje informacje na temat osoby w zakresie i kontekście w jakim wymaga tego obsługa hotelu\&. Jest klasą abstrakcyjną\&. "
.ti -1c
.RI "class \fBPobyt\fP"
.br
.RI "Klasa Pobyt zawiera informacje na temat pobytu grupy gości oraz pozwala stwierdzić, czy rezerwacja takiegoż jest w ogóle możliwa\&. "
.ti -1c
.RI "class \fBPodgladGosci\fP"
.br
.RI "Logika interakcji dla klasy PodgladGosci\&.xaml\&. "
.ti -1c
.RI "class \fBPodgladPokoi\fP"
.br
.RI "Logika interakcji dla klasy PodgladPokoi\&.xaml\&. "
.ti -1c
.RI "class \fBPodgladPracownikow\fP"
.br
.RI "Logika interakcji dla klasy PodgladPracownikow\&.xaml\&. "
.ti -1c
.RI "class \fBPokoj\fP"
.br
.RI "Klasa Pokój przechowuje informacje na temat pojedynczego pokoju i definiuje operacje, które można wykonywać na nim lub na grupie jej instancji\&. "
.ti -1c
.RI "class \fBPracownik\fP"
.br
.RI "Klasa pracownik przechowuje informacje na temat pracownika hotelu\&. "
.ti -1c
.RI "class \fBRejestrGosci\fP"
.br
.RI "Klasa RejestrGosci posiada informacje na temat gosci zarejestrowanych w hotelu\&. Pozwala na zapis i odczyt rejestru a także wyszukiwanie gosci czy pobytów spełniających wskazane warunki\&. "
.ti -1c
.RI "class \fBTworzenieNowegoPokojuException\fP"
.br
.RI "Wyjątek jest wywoływany w sytuacji, kiedy dochodzi do próby stworzenia pokoju\&. "
.ti -1c
.RI "class \fBZlyPeselException\fP"
.br
.RI "Wyjątek wywoływany jest w sytuacji, kiedy podano nieprawidłowy pesel\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEnumWydzial\fP { \fBRecepcja\fP, \fBHousekeeping\fP, \fBKuchnia\fP, \fBAdministracja\fP }"
.br
.ti -1c
.RI "enum \fBEnumBudynek\fP { \fBA\fP, \fBB\fP, \fBC\fP, \fBD\fP }"
.br
.ti -1c
.RI "enum \fBEnumPietro\fP { \fBpierwsze\fP = 1, \fBdrugie\fP = 2, \fBtrzecie\fP = 3 }"
.br
.ti -1c
.RI "enum \fBEnumNrPokoju\fP { \fBjeden\fP = 1, \fBdwa\fP = 2, \fBtrzy\fP = 3, \fBcztery\fP = 4, \fBpiec\fP = 5 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
