.TH "Hotel.Adres" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.Adres \- Klasa Adres ma za zadanie przechowanie informacji na temat adresu osób\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdres\fP (string ulica, int nrDomu, string miejscowosc, string kodPocztowy)"
.br
.ti -1c
.RI "\fBAdres\fP (string ulica, int nrDomu, int nrLokalu, string miejscowosc, string kodPocztowy)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Metoda zwraca informacje na temat adresu zamieszkania osoby\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUlica\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNrDomu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNrLokalu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMiejscowosc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBKodPocztowy\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Klasa Adres ma za zadanie przechowanie informacji na temat adresu osób\&. 
.SH "Member Function Documentation"
.PP 
.SS "override string Hotel\&.Adres\&.ToString ()\fC [inline]\fP"

.PP
Metoda zwraca informacje na temat adresu zamieszkania osoby\&. 
.PP
\fBReturns\fP
.RS 4
Tekst\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
