.TH "Hotel.Osoba" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.Osoba \- Osoba reprezentuje informacje na temat osoby w zakresie i kontekście w jakim wymaga tego obsługa hotelu\&. Jest klasą abstrakcyjną\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHotel\&.Gosc\fP, and \fBHotel\&.Pracownik\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOsoba\fP (string imie, string nazwisko, string pesel, \fBAdres\fP adres, DateTime dataUrodzenia)"
.br
.ti -1c
.RI "int \fBWiek\fP ()"
.br
.RI "Metoda ma za zadanie odpowiedzenie na pytanie o wiek osoby\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBImie\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNazwisko\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBDataUrodzenia\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPesel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAdres\fP \fBAdres\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Osoba reprezentuje informacje na temat osoby w zakresie i kontekście w jakim wymaga tego obsługa hotelu\&. Jest klasą abstrakcyjną\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Hotel\&.Osoba\&.Wiek ()"

.PP
Metoda ma za zadanie odpowiedzenie na pytanie o wiek osoby\&. 
.PP
\fBReturns\fP
.RS 4
Wiek osoby w latach\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
