.TH "Hotel.TworzenieNowegoPokojuException" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.TworzenieNowegoPokojuException \- Wyjątek jest wywoływany w sytuacji, kiedy dochodzi do próby stworzenia pokoju\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Wyjątek jest wywoływany w sytuacji, kiedy dochodzi do próby stworzenia pokoju\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
