.TH "Hotel.PodgladGosci" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.PodgladGosci \- Logika interakcji dla klasy PodgladGosci\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SH "Detailed Description"
.PP 
Logika interakcji dla klasy PodgladGosci\&.xaml\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
