.TH "Hotel.Pobyt" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.Pobyt \- Klasa Pobyt zawiera informacje na temat pobytu grupy gości oraz pozwala stwierdzić, czy rezerwacja takiegoż jest w ogóle możliwa\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPobyt\fP (DateTime poczatek, DateTime koniec, \fBPokoj\fP pokoj, List< \fBGosc\fP > pozostaliGoscie, \fBPracownik\fP zakladajacyRezerwacje)"
.br
.ti -1c
.RI "int \fBDlugosc\fP ()"
.br
.RI "Metoda ma za zadanie podanie informacji na temat długości pobytu\&. "
.ti -1c
.RI "int \fBLiczbaOsob\fP ()"
.br
.RI "Metoda ma za zadanie podanie ilości osób z grupy przypisanej do pobytu\&. "
.ti -1c
.RI "decimal \fBCena\fP ()"
.br
.RI "Metoda informuje o cenie łącznej za pobyt, zależnej od ilości członków, wieku oraz długości pobytu\&. "
.ti -1c
.RI "bool \fBCzyNachodzi\fP (DateTime poczatek2, DateTime koniec2)"
.br
.RI "Metoda ma na celu zwrócenie informacji na temat tego, czy pobyt nachodzi na pewien inny\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Metoda wypisuje informacje na temat pobytu: jej początek, koniec, długość, gości, ich liczbę, cenę etc\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBPoczatek\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBKoniec\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPokoj\fP? \fBPokoj\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBGosc\fP > \fBPozostaliGoscie\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPracownik\fP \fBZakladajacyRezerwacje\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIdPobytu\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Klasa Pobyt zawiera informacje na temat pobytu grupy gości oraz pozwala stwierdzić, czy rezerwacja takiegoż jest w ogóle możliwa\&. 
.SH "Member Function Documentation"
.PP 
.SS "decimal Hotel\&.Pobyt\&.Cena ()\fC [inline]\fP"

.PP
Metoda informuje o cenie łącznej za pobyt, zależnej od ilości członków, wieku oraz długości pobytu\&. 
.PP
\fBReturns\fP
.RS 4
Cena\&. 
.RE
.PP

.SS "bool Hotel\&.Pobyt\&.CzyNachodzi (DateTime poczatek2, DateTime koniec2)\fC [inline]\fP"

.PP
Metoda ma na celu zwrócenie informacji na temat tego, czy pobyt nachodzi na pewien inny\&. 
.PP
\fBParameters\fP
.RS 4
\fIpoczatek2\fP początek pobytu\&. 
.br
\fIkoniec2\fP koniec pobytu\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Wartość logiczna\&. 
.RE
.PP

.SS "int Hotel\&.Pobyt\&.Dlugosc ()"

.PP
Metoda ma za zadanie podanie informacji na temat długości pobytu\&. 
.PP
\fBReturns\fP
.RS 4
Długosć pobytu w dniach\&. 
.RE
.PP

.SS "int Hotel\&.Pobyt\&.LiczbaOsob ()"

.PP
Metoda ma za zadanie podanie ilości osób z grupy przypisanej do pobytu\&. 
.PP
\fBReturns\fP
.RS 4
Ilość osób\&. 
.RE
.PP

.SS "override string Hotel\&.Pobyt\&.ToString ()\fC [inline]\fP"

.PP
Metoda wypisuje informacje na temat pobytu: jej początek, koniec, długość, gości, ich liczbę, cenę etc\&. 
.PP
\fBReturns\fP
.RS 4
Tekst\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
