.TH "Hotel.Pracownik" 3 "Fri Jan 26 2024" "Dokumentacja Projektu "System obsługi hotelu"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hotel.Pracownik \- Klasa pracownik przechowuje informacje na temat pracownika hotelu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotel\&.Osoba\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPracownik\fP (string imie, string nazwisko, string pesel, \fBAdres\fP adres, DateTime dataUrodzenia, EnumWydzial wydzial, DateTime dataWstapienia)"
.br
.ti -1c
.RI "int \fBLataDoswiadczenia\fP ()"
.br
.RI "Metoda zwraca informację na temat lat doświadczenia pracownika\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHotel\&.Osoba\fP
.in +1c
.ti -1c
.RI "\fBOsoba\fP (string imie, string nazwisko, string pesel, \fBAdres\fP adres, DateTime dataUrodzenia)"
.br
.ti -1c
.RI "int \fBWiek\fP ()"
.br
.RI "Metoda ma za zadanie odpowiedzenie na pytanie o wiek osoby\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "EnumWydzial \fBWydzial\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBDataWstapienia\fP\fC [get, set]\fP"
.br
.in -1c

Properties inherited from \fBHotel\&.Osoba\fP
.in +1c
.ti -1c
.RI "string \fBImie\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNazwisko\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBDataUrodzenia\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPesel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAdres\fP \fBAdres\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Klasa pracownik przechowuje informacje na temat pracownika hotelu\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Hotel\&.Pracownik\&.LataDoswiadczenia ()"

.PP
Metoda zwraca informację na temat lat doświadczenia pracownika\&. 
.PP
\fBReturns\fP
.RS 4
Ilość lat doświadczenia\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentacja Projektu 'System obsługi hotelu' from the source code\&.
